ansible_become_pass: ENC[AES256_GCM,data:KlW2irIpI69IUQ==,iv:jhsi8rRf4HrdI7pspRCMFmS3s0Hunk4qLdrzj8WpsO8=,tag:0zgtwJtyK2uFc359CmPPtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwptqhq4nlycn8qfje43yrl5f7vz6qyw93wk6tr4a9m6uuxzvsqsxfd0fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR2taMENWWTlqeXVOUEli
            dUhIa0FDMFJIaEJLRmQ4WGxHcG4zK1ZKSEc0CllzWC9zMzNVbGZ4L3J6eDA1emt6
            VFFoVnd5WmphUk51WXpSNVZ2bkxaVXcKLS0tIEpiWXVRZ1VoZG9wMmthendQblpR
            cGdqVkoxRHRrSU92VmdiWFo3VkpmUEEKf2BoF9GR3TcVtTCRrQX7CvoNlNKBFtgt
            0QAk+bf0s+2bzRZok5ZfpJiVwoeGYTIl0BJM9o4iC3FiefEvj7v6RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T04:25:15Z"
    mac: ENC[AES256_GCM,data:wrEJXNeg0CMJSXY54h9IQ/B4sNPEtb5ZD4utEt3h1StehH7neFDX27F8Vle1/d7kjabc0ruM3vgIhfTqwXSZdUTKZCj/30iS4fj4b1p44Tn+DKI8kSbGGG9xNf6Ji601O3SNMxBcmE9J8HyW7PsIMbjurttXtB/YjyjJLLyklFA=,iv:2VNItKLqulblFwo4i2L5NOYmsJDJ8EFVznf94VjmcoY=,tag:G7lOlMbYFQoQB80RiWDMCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
