apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:SKzY78kPxj8Y,iv:MJFHGzyg7QZFlTg9qCIHRqIvDn9qqqS7OtpvQY5W9NE=,tag:7jOLbkpq9mm+HCJVzamLLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwptqhq4nlycn8qfje43yrl5f7vz6qyw93wk6tr4a9m6uuxzvsqsxfd0fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWE9qSU9rd3p6QnAyYldr
            Y0NHMkZNeHhSNGlnL0FNNUZLWDcxUkF2dVQ4CjJPSW9kbDRtOW56SXZPMTRzVjZ6
            SXJscjhZVzJxTk1rTExRYnZBc3IrVjAKLS0tIERmT3ViSTRmVTk3RkdXRlVwbVpI
            MUpsWlFrekxDYXA4NVhhYXYyYUVhNzQKnEA4mWhIxprG7c4ixB1OAULV34fSujKj
            mpUj2kTmnoWHMnL7OV/HXtvusqfRq32uzdZr4USS9AEJX2HvHL6BAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T01:54:34Z"
    mac: ENC[AES256_GCM,data:TRJPn+T0Ger1EBcSA+QlnGK0yEETXE8ELMd8kt/KHa2qskb0jSSNVojqAE2D/KsQKtIjqnQR8Yf8jKKugYhH1uVeJTvTYVvl3x7t1Kww4vEqL9B6WNPQwhKA98PbpX5Mn59gkj5nasg3mu1d/ZC4xDrMPL6MgiuM+Zh9/V3nkGo=,iv:zyewYaYeWFYsyOlVdSa78fwnuIFMBUhk4sFmttvkJ7I=,tag:DAhfBJ2f24r8Tl9GORjXQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
