apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NPycK8Kgm/4mSo6r+Ptzqkd3rkJ8n+Hsx9adX8ciRtDyWLqQnSjpKw==,iv:y3szo1RPW4lUmUOiViVvqTyoNWXo99Kb0Y/by3xSaLU=,tag:gqPOa6JpTdhKoFNa/OCWzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwptqhq4nlycn8qfje43yrl5f7vz6qyw93wk6tr4a9m6uuxzvsqsxfd0fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUalp3VTZXcFMzdzJKOWZ2
            anBtQTU3Zk5UQ2hRekNFNERuSTlVSldxTkd3CnJ3eWxWbUw1Qk5Ka2pOWHowMlh6
            YXF4ZWF5OE5pS0pXa2NXQ0k2c3VzTTgKLS0tIFI5Q291QmxyM3JvWnEwR1FCWlJ5
            ZWtYU3Bacm8xc1hQWGVXSG1OU1lidHMK9j4soL0fVFd38HJ9IguywfdAG+CnydX4
            8is1CH0qpx8lm3eb0z20UuvIb9XeOonxoGe+vK9LWwGQe0gS9AKOaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T04:25:48Z"
    mac: ENC[AES256_GCM,data:PMkvEyWJBxkP1MNyb/vieuX28wyM/2iLyrNTp1gMzOVewhtu+SSoVtjzbm2jcMjnnx1Oi6H/F4BwQkAjrERWqGGoeFPM1zgetVOw1UdLCFnWSR2GyiLKea27V7WZJl2fausGHstL8KO4XOb7V4O38KPg93WF+0P3DFCVvGeadmQ=,iv:E8djXARDmlZ5oIIBYvA2iER1R8GyfUUj7h2mPp6pZYQ=,tag:0L7EtTidF24vvEihws3glA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
