apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:m49BKX+i46XkUSsJNJVlAugZ70wks+4U3rvkQbcQcivVQ2s67ja1mA==,iv:WBZwGUnSLaF7DH8T8N9QZv166BxMJBzxQNEI8y/7IkE=,tag:6/zt+3ZrqI1Lmns+9lV9Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwptqhq4nlycn8qfje43yrl5f7vz6qyw93wk6tr4a9m6uuxzvsqsxfd0fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OFI1blJBdDZiUVBkZ1hW
            WG9jajA0dXE3RnRJK2RJaldya1ZHVk9wbFJBCkpvb0dZanFoVEpLVHh5MmxqSVhJ
            UWdVMW5OZm8zS1dNTzQ4QjJXOTJUMUEKLS0tIGg5d1hFSnc5WTltc0ZvZnArMklq
            dnVwMEw3N3dsRk4yYlpuYXhXNlV0ZUkKqXe0MqJNAGjFyUzi6R1vI7skRxF1zE7s
            4n2ReBau7TFh8+KxnyMzuQ2qxXI3sbfj1+FvRkoM/wiuo+5Wj7FaAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T01:54:34Z"
    mac: ENC[AES256_GCM,data:8p4PfJwCsULQFKChth6h4I2WedGgU8j+ZvqGuEohwob22l+ghyp73mO8ChsTWitVN8bHl10ivsEJ0JPe7jYqfelVpZjX4qqVpAwGxUmFSPyMDx0+M4MvXLpt7dKRk0fR//NICP3duH/Ua77Lfvc5w+OMWt4iV+QXATZvj0AL5CU=,iv:c9GEEiqRuMEbWMW2ed664T+iRypZ9qqTMZorR2NUA8Y=,tag:ZZ3jfXPgCs5mmP52TI2aHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
