apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tP2s+Ux5rRHrzyDOw8br9mWtH7I=,iv:NdB3I+2U7QC4r3rUjhowxcMQKIg3pZqYTs7JN8wQdqA=,tag:y6v/JwR7i2lRXSs6WOCfFg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XNdHxN3tPtL7csLPTavgoRjFg4e6f6D4V3nTrr2wuby8Hjs9,iv:Z3ow6QvRjOC2T96BLopAuDWYq16xrdr6N8MMZPYw/Lo=,tag:ns9/9MG4inObwdRIMdCW3A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:cDRh8VR/qnRfDQ==,iv:uIjyz2I/V0meVs0WiNHw3FUM2VvaBDmii3YcVUaNGqw=,tag:vdg24RDgW0u0fponNET3Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dwptqhq4nlycn8qfje43yrl5f7vz6qyw93wk6tr4a9m6uuxzvsqsxfd0fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQWxnc2lKTFovQ01wWFF0
            LzhxUW1LRHoxOE1Ndjllc09WMVRFUzQyVERzCnBQMlZxZlBtSENTUjNXemVFd1JN
            aGtON0l5K3FZWlA2NzBVTnQydFl3cjAKLS0tIHlVVnFCTzhJK0ljOGtHM2ZQUTNh
            ZlRBU3BtK1dSbDhyK3FSWlkyQ2R6VUkKmkOIPEwiHiElMu6A3qDj/bGhyS+rE1wO
            q1k8Ev7u/czQT0ipAw/mvdFvYN0c2/gBbXb1DZ5Gay75ZoevjlX87w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T01:54:33Z"
    mac: ENC[AES256_GCM,data:hu8A5utGSPrCxWRaYrwoS4SHxXCAFr/nS9i6G5MpDGhES9+8dBHEqKVh6Lpfl0+Tb1uZHNjdpMeHR3GB33g5joOnXy8XLnz2xa0eO0pU38gDZpqGW+8wxt5yqbK5raQUqGKGnI9iwSXY42tpWX7LIv6Wkj1czI00Cfe7SkQG7co=,iv:ie9OWgTM8W5ReURpuJSw13UjMfImw8/i82zWiGVtHos=,tag:8pO/Xjz+wmBgdWPftjEXhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
